project:
  type: website
  output-dir: docs
  
website:
  title: "아영의 웹사이트"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
      - href: hw1.qmd
        text: 숙제1
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



